import { createRequire } from "node:module";

import type { DomParser } from "./types.ts";

/**
 * DOM node type codes from the WHATWG Living Standard.
 * Numeric values are used directly because the global `Node` object is
 * not available in linkedom or Bun — only in browser environments.
 */
export const NODE_TYPE = {
  CDATA_SECTION: 4,
  COMMENT: 8,
  DOCUMENT: 9,
  DOCUMENT_FRAGMENT: 11,
  ELEMENT: 1,
  TEXT: 3,
} as const;

/** Tags that linkedom auto-generates inside the document element when
 * parsing HTML fragments — they must be excluded from content output. */
const STRUCTURAL_TAGS: ReadonlySet<string> = new Set([
  "base",
  "body",
  "head",
  "html",
  "link",
  "meta",
  "title",
]);

/** Void HTML elements that never have a closing tag. */
const VOID_ELEMENTS: ReadonlySet<string> = new Set([
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]);

/** linkedom module shape — avoids a static import so the bundler can
 * externalise the dependency and browsers never load it. */
interface LinkedomModule {
  parseHTML: (html: string) => { document: Document };
}

/** Lazily loaded linkedom instance, cached after first access */
let linkedomModule: LinkedomModule | null = null;

/**
 * Synchronously load and cache the linkedom module.
 *
 * linkedom is a devDependency used only in Node/Bun environments.
 * In browsers the native `DOMParser` global is available and this
 * function is never called.
 *
 * @throws {Error} when linkedom is not installed.
 */
function loadLinkedom(): LinkedomModule {
  if (linkedomModule !== null) {
    return linkedomModule;
  }

  linkedomModule = createRequire(import.meta.url)("linkedom") as LinkedomModule;

  return linkedomModule;
}

/** Whether the current environment exposes the browser-native DOMParser */
function hasNativeDomParser(): boolean {
  return typeof globalThis.DOMParser !== "undefined";
}

/** Browser-native DOMParser wrapper */
function createNativeParser(): DomParser {
  return {
    parse(html: string): Document {
      const parser = new globalThis.DOMParser();
      return parser.parseFromString(html, "text/html");
    },
  };
}

/** linkedom-backed parser for Node / Bun / CLI environments */
function createLinkedomParser(): DomParser {
  return {
    parse(html: string): Document {
      const { parseHTML } = loadLinkedom();
      return parseHTML(html).document;
    },
  };
}

/**
 * Safely access `doc.body`.
 *
 * linkedom throws when accessing `body` (which delegates through
 * `head` → `documentElement.firstElementChild`) for empty or
 * malformed HTML. This wrapper returns `null` in those cases.
 */
function safeGetBody(doc: Document): Element | null {
  try {
    return doc.body;
  } catch {
    return null;
  }
}

/**
 * Escape a string for safe use as an HTML attribute value.
 */
function escapeAttribute(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}

/**
 * Serialize a DOM `Node` back into an HTML string.
 *
 * Uses the browser-native `XMLSerializer` when available. In
 * linkedom environments the node's own `toString()` / `outerHTML`
 * accessors are used instead.
 *
 * @public
 */
export function serialize(node: Node): string {
  if (typeof globalThis.XMLSerializer !== "undefined") {
    return new globalThis.XMLSerializer().serializeToString(node);
  }

  // linkedom: Element.outerHTML exists; Document.toString() returns source
  const anyNode = node as unknown as {
    outerHTML?: string;
    toString: () => string;
  };
  if (anyNode.outerHTML !== undefined && anyNode.outerHTML !== "") {
    return anyNode.outerHTML;
  }
  return anyNode.toString();
}

/**
 * Checks whether a node is a structural element auto-generated by
 * linkedom when parsing HTML fragments (html, head, body, etc.).
 *
 * @public
 */
export function isStructuralElement(node: Node): boolean {
  if (node.nodeType !== NODE_TYPE.ELEMENT) {
    return false;
  }
  const tag = (node as Element).tagName.toLowerCase();
  return STRUCTURAL_TAGS.has(tag);
}

/**
 * Serialize a node to HTML, **excluding** structural elements that
 * linkedom auto-generates inside document fragments.
 *
 * Unlike {@link serialize}, this function walks the tree and skips
 * `head`, `body`, `html`, etc. so the output contains only content.
 * It is the preferred serialiser for cleaned fragment content.
 *
 * @public
 */
export function serializeContent(node: Node): string {
  if (node.nodeType === NODE_TYPE.TEXT) {
    return node.textContent ?? "";
  }

  if (node.nodeType === NODE_TYPE.COMMENT) {
    return "";
  }

  if (node.nodeType !== NODE_TYPE.ELEMENT) {
    return "";
  }

  // Skip structural elements entirely
  if (isStructuralElement(node)) {
    return "";
  }

  const element = node as Element;
  const tag = element.tagName.toLowerCase();
  const attrs = Array.from(element.attributes)
    .map((attr) => `${attr.name}="${escapeAttribute(attr.value)}"`)
    .join(" ");
  const prefix = attrs ? ` ${attrs}` : "";

  if (VOID_ELEMENTS.has(tag)) {
    return `<${tag}${prefix} />`;
  }

  // Recursively serialize children, skipping structural elements
  const children = Array.from(element.childNodes)
    .filter((child) => !isStructuralElement(child))
    .map((child) => serializeContent(child))
    .join("");

  return `<${tag}${prefix}>${children}</${tag}>`;
}

/**
 * Extract the content-bearing nodes from a `Document` or `Element`.
 *
 * For full HTML documents the body's children are returned. When the input
 * is a fragment (linkedom leaves the body empty) the document-level
 * children are returned, excluding auto-generated structural tags.
 *
 * @public
 */
export function getContentNodes(node: Element | Document): Node[] {
  if (node.nodeType === NODE_TYPE.DOCUMENT) {
    const doc = node as Document;
    const body = safeGetBody(doc);
    if (body && body.children.length > 0) {
      return Array.from(body.childNodes);
    }
    // Fragment: content lives at the document level
    return Array.from(doc.childNodes).filter(
      (child) => !isStructuralElement(child)
    );
  }

  // Element: return children, filtering structural tags that linkedom
  // may have injected inside the documentElement
  return Array.from(node.childNodes).filter(
    (child) => !isStructuralElement(child)
  );
}

/**
 * Return the appropriate DOM parser for the current environment.
 *
 * Browsers use the native `DOMParser` global; Node.js / Bun / CLI
 * environments fall back to linkedom.
 *
 * @public
 */
export function getDomParser(): DomParser {
  if (hasNativeDomParser()) {
    return createNativeParser();
  }
  return createLinkedomParser();
}

/**
 * Characters that should be stripped from visible text output.
 * Includes zero-width joiners, non-breaking spaces, soft hyphens,
 * and other invisible Unicode characters that WYSIWYG editors inject.
 */
export const INVISIBLE_CHARS =
  /\u200B|\u200C|\u200D|\u200E|\u200F|\u00AD|\u00A0/g;

/**
 * Strip invisible characters from text content.
 *
 * @public
 */
export function stripInvisibleChars(text: string): string {
  return text.replace(INVISIBLE_CHARS, "");
}
